---
- hosts: "{{ host | default('localhost') }}"
  become: true
  vars_files:
    - "roles/{{ ansible_distribution | lower }}/vars/main.yml"
  roles:
    - { role: ubuntu, when: "ansible_distribution == 'Ubuntu'", tags: [os] }
    - { role: macosx, when: "ansible_distribution == 'MacOSX'", tags: [os] }
