export PATH=$HOME/Code/github/github/bin:$HOME/Code/bin:$HOME/bin:/usr/local/bin:$PATH
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(
  docker
  git
  github
  httpie
  systemd
  vscode
)

source $ZSH/oh-my-zsh.sh

# source custom stuff
source $HOME/.aliases
source $HOME/.exports
source $HOME/.functions