---
- name: install classic snaps
  snap:
    name:
      - go
      - code
      - slack
      - microk8s
      - kubectl
      - task
    classic: yes

- name: install snaps
  snap:
    name:
      - docker
      - lxd
      - etcd
      - chromium
      - terraform
      - http
      - spotify

- name: install beta snaps
  snap:
    name: conda
    channel: beta
