---
- name: add user to the sudoers
  copy:
    dest: "/etc/sudoers.d/rossedman"
    content: "rossedman  ALL=(ALL)  NOPASSWD: ALL"

- name: create ssh directory
  file:
    path: /home/rossedman/.ssh
    state: directory
    mode: '0700'

- name: disable password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: "PasswordAuthentication no"
    state: present
    backup: yes

- name: disable root login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: "PermitRootLogin no"
    state: present
    backup: yes
  notify:
    - restart ssh
